### ISSUE TITLE
Permettre l'intégration sur un site tiers

### ISSUE THREAD

**Issue by swirly** [codepuzzle-io/www.codepuzzle.io#10]
Actuellement, codepuzzle est un site indépendant, et ce dépôt représente l'application.
Ce serait chouette de pouvoir avoir un composant web que l'on puisse intégrer dans un cours en ligne. Actuellement, on peut toujours faire une iframe, mais avoir la possibilité d'intégrer complétement à un site serait un plus

Je suis conscient que cela n'a sans doute rien d'une priorité.

**Comment by laurentabbal** [comment]
Bonjour,
Tant que le site n'est pas stable, c'est difficilement envisageable. Mais c'est noté.
