### ISSUE TITLE
problème avec les tests

### ISSUE THREAD

**Issue by Sylvain1978** [codepuzzle-io/www.codepuzzle.io#11]
Bonjour, je suis en train de faire des défis sur les tris. Les tests marchent bien avec de simples listes mais lorsque j'essaie de faire un tri par insertion sur une liste de tuples, il ne se passe rien lorsque je clique sur "Vérifier"

from IPython.display import IFrame
IFrame('https://www.codepuzzle.io/IDZFMD', width='100%', height=600)

**Comment by laurentabbal** [comment]
Bonjour. Merci pour l'info. Je pense que ce sont les guillemets qui posent problème. Ils ne sont pas correctement filtrés apparemment. Je vais regarder ça.
Avec des guillemets simples, ça marche?
