### ISSUE TITLE
Problème avec délimiteur de chaine de caractères " dans le champ message des tests

### ISSUE THREAD

**Issue by frederic-junier** [codepuzzle-io/www.codepuzzle.io#15]
Salut Laurent,
Super ta nouvelle appli, petit bogue visiblement si on utilise le délimiteur " pour le message dans un cas de test. Pas de souci avec '

**Comment by laurentabbal** [comment]
Normalement, c'est corrigé.

**Comment by frederic-junier** [comment]
Super, merci 👍
