### ISSUE TITLE
Le code à compléter n'apparaît pas

### ISSUE THREAD

**Issue by fabricelallemand15** [codepuzzle-io/www.codepuzzle.io#16]
Bonjour

j'ai défini un entraînement avec un code à compléter.
Lorsque je vais sur le lien élève, le code à compléter n'apparaît pas. Voir captures d'écran jointes.

![(440)Snap_2023 11 11](https://github.com/codepuzzle-io/www.codepuzzle.io/assets/19834776/454ae11c-4e69-4c8d-aa3e-097ff564b43f)
![(441)Snap_2023 11 11](https://github.com/codepuzzle-io/www.codepuzzle.io/assets/19834776/ba0912a0-d6f0-48a4-88f9-5da90788ef26)

**Comment by fabricelallemand15** [comment]
J'ai compris l'origine du bug : les caractères accentués que j'ai utilisés dans un commentaire inclus dans le code. Ceux-ci ne sont pas supportés.

**Comment by laurentabbal** [comment]
Bonjour,
C'est toujours le cas? Je n'ai pas réussi à reproduire le problème.
