### ISSUE TITLE
Test ne s'exécute pas

### ISSUE THREAD

**Issue by fabricelallemand15** [codepuzzle-io/www.codepuzzle.io#17]
Chez moi les tests ne s'exécutent pas non plus. Pourtant, ils semblent s'exécuter chez d'autres testeurs ... https://www.codepuzzle.io/EV7BKF5U

**Comment by laurentabbal** [comment]
Bonjour,
C'est toujours le cas?
Il y avait un bug avec les tests qui comportaient des ".
