### ISSUE TITLE
liens élève et QRcode

### ISSUE THREAD

**Issue by patroncin** [codepuzzle-io/www.codepuzzle.io#18]
Bonjour,
Je tente de faire fonctionner l'appli "codepuzzle" pour faire un devoir en 1ère NSI. L'étape "création d'un exercice" est effectuée et validée (j'ai choisi un puzzle de Parsons). L'étape création d'une classe n'est qu'en partie réussie car je peux lancer l'exercice sans identification. 
Sur la 1ère copie d'écran, il me manque les deux cadres "code secret" et "lien élèves" montrés dans le tuto.
![image](https://github.com/codepuzzle-io/www.codepuzzle.io/assets/51435802/ea830940-d61a-4158-8392-3db61d0dec71)
La 2ème copie d'écran donne la suite de la page https://www.codepuzzle.io/classe-console/B6MW7LG8QKJ3?i
![image](https://github.com/codepuzzle-io/www.codepuzzle.io/assets/51435802/d259945a-8875-407e-ba92-434bc41ad675)
Je reste bloqué sur le fait que je ne peux tester le devoir en connexion par identification. Si vous pouviez m'aider?
Merci pour l'attention que vous voudrez bien porter à ma demande.
Cordialement,
Patrick RONCIN
patrick.roncin@ac-rennes.fr

**Comment by laurentabbal** [comment]
Bonjour. Il y a quelque chose d'étrange en effet. Je vais regarder cela.

**Comment by laurentabbal** [comment]
En fait, non, c'est normal.
"L'étape création d'une classe n'est qu'en partie réussie car je peux lancer l'exercice sans identification."
C'est normal. Le mode avec lien secret permet d'utiliser une classe sans compte. Mais comme vous avez créé la classe avec un compte, il est préférable de passer par la console de l'enseignant, d'aller dans "CLASSES" et de cliquer sur le bouton "voir".
"Devoirs" est à part et ne s'intègre pas dans "Classe". "Classe" est fait pour proposer des défis et des puzzles, pas des devoirs. Chaque élève a un lien unique individuel (indiqué dans la colonne "console"). Avec ce lien l'élève peut voir les activités à faire et accéder aux activités proposée par l'enseignant.

**Comment by patroncin** [comment]
Merci pour votre réponse. 
Je poursuis mes essais en tenant compte de vos retours. Là, je bloque de nouveau sur le devoir
 https://www.codepuzzle.io/devoir-console/M6TG5VPXA2U9 
effectué par 2 élèves "eleve1" et "eleve2". Les 'assert' du code enseignant ne fonctionne pas que ce soit "avant rendu" ou "après rendu".
Si vous voulez bien jeter un œil(?)
Patrick RONCIN

**Comment by laurentabbal** [comment]
Bonjour,
Que voulez-vous dire par "ne fonctionnent pas"?
Je ne vois pas de problème avec le premier programme. Et, pour le deuxième, il y a une erreur dès la ligne 4.

**Comment by patroncin** [comment]
Bonjour,
Désolé, j'ai fait une erreur dans mes saisies "élève" et j'ai mal compris le fonctionnement de l'interface, en effet, le code enseignant exécuté seul (uniquement les assert faisant appel à la fonction xor) dans ce cas retourne une erreur "Erreur ligne 1 NameError: name 'xor' is not defined" puisque la fonction xor est déclarée dans la fenêtre élève. 
Au vu de vos explications d'hier, il n'apparait pas possible de mettre dans un devoir un "puzzle de Parsons, c'est bien cela?
En tout cas merci pour ces outils fort utiles pour la spécialité NSI.
Bien cordialement,
Patrick RONCIN

**Comment by laurentabbal** [comment]
Pour proposer des puzzles ou des défis aux élèves et suivre leur progression, il faut le faire via une classe. Ainsi on peut voir si les élèves ont réussi à faire un puzzle ou un défi.
