### ISSUE TITLE
Booléen "False" - Problème de validation de défis.

### ISSUE THREAD

**Issue by badjeroud** [codepuzzle-io/www.codepuzzle.io#21]
Salut.
Si je peux faire remonter une difficulté sur une validation d'exercice.

Je suis dans la partie "Défis" et j'essaie de faire valider une sortie à False (booléen).
(Mon exercice initial était plus compliqué, j'ai juste simplifié mon exercice pour isoler le problème)

J'ai donc simplifié mon code et je n'ai plus que pour consigne : 
Ecrire le booléen False.

https://www.codepuzzle.io/DL4Y7

Mon test est : 
Condition : False
Message : False

Mon problème est que je ne parviens jamais à faire valider cet exercice :

Dans l'interface de résolution du défis, j'ai l'impression que d'entrer simplement

> False

Dans la partie code, se transformera en 
> false

lors de l'exécution (un F qui se transforme en f)

J'ai essayé un peu toutes les combinaisons, mais je ne suis pas parvenu à faire valider une sortie booléen à False.

Je précise que je n'ai pas eu ce problème avec True ( et ses déclinaisons "True" et Vrai) qui me semble être correctement traité.
Cordialement,

**Comment by laurentabbal** [comment]
Bonjour,
Je ne vois pas condition dans le test de cet exemple. Il faudrait quelque chose comme a == False.

**Comment by laurentabbal** [comment]
Il faut une condition. Or, ici il n'y a pas de condition.
Le format est: assert condition, message

![image](https://github.com/codepuzzle-io/www.codepuzzle.io/assets/592821/a053df43-ed0b-4d4f-b029-f4c0fa7bf491)

**Comment by badjeroud** [comment]
Ok, désolé d'avoir ouvert une issue alors que c'était simplement moi qui n'ai pas su prendre le temps de comprendre le fonctionnement de votre outil.

Merci de votre travail.
Cdt
