### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by DelphNSI** [codepuzzle-io/www.codepuzzle.io#22]
Bonjour

J'ai créé un défi et un devoir mais au moment de valider, j'ai une erreur 500 | ERREUR SERVEUR...

J'en profite pour vous dire un énorme merci pour ce site qui me semble très pratique !

Bonne journée

Delphine

**Comment by laurentabbal** [comment]
Bonjour,
Désolé pour cette réponse un peu tardive. 
Cela doit être un problème de caractères spéciaux mal interprétés par Markdown. Il me faudrait l'adresse email du compte pour le corriger. Vous pouvez l'envoyer à l'adresse email qui est indiquée sur le site.
Je vais changer la gestion du Markdown pour que ce problème ne se reproduise plus. Il va me falloir une petite semaine.

**Comment by laurentabbal** [comment]
Le problème avec le Markdown et les caractères spéciaux est corrigé avec la v3.
