### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by DelphNSI** [codepuzzle-io/www.codepuzzle.io#24]
Bonjour

j’ai une erreur 500 quand je veux créer un devoir…
Avez-vous un moyen de corriger cette erreur ?

merci, Cordialement 

Delphine

**Comment by laurentabbal** [comment]
Bonjour,
J'ai fait un test et je n'ai pas rencontré de problème. Vous avez plus de détails?

**Comment by jmzogit** [comment]
Bonjour, 
J'ai le meme probleme. 
Je viens de poster le log.
je suis en Afrique du Sud, peut-être que cela vient de la liaison à l'international ?
