### ISSUE TITLE
Utilisation dans un notebook Jupyter

### ISSUE THREAD

**Issue by Sylvain1978** [codepuzzle-io/www.codepuzzle.io#3]
Bonjour,
J'ai intégré un Puzzle dans un notebook Jupyter  mais après avoir cliqué sur "vérifier", l'option "éditer la cellule pour copier le code" n'apparait pas.
Est ce qu'il y a une solution pour le faire depuis un notebook Jupyter svp? 
merci d'avance
Sylvain

**Comment by nherminier** [comment]
Bonjour, J'ai la même attente sur Jupyter. Avez-vous trouvé la solution? Merci!!!

**Comment by laurentabbal** [comment]
Oula, j'ai complètement oublié de répondre à la première question. Désolé.

Je vais regarder tout ça. Je devrais pouvoir apporter une réponse dans les prochains jours car je suis en train de travailler sur l’intégration de Code Puzzle dans Capytale.

**Comment by laurentabbal** [comment]
Le bug est corrigé. Encore quelques tests et le site sera mis à jour (en début de semaine si tout va bien).

**Comment by laurentabbal** [comment]
Corrigé et en ligne!
