### ISSUE TITLE
Problème avec le mode classe

### ISSUE THREAD

**Issue by Sylvain1978** [codepuzzle-io/www.codepuzzle.io#30]
Bonjour,
Pour un de mes élèves, ses exercices validés apparaissent bien sur son interface mais pas sur mon suivi des activités.
Merci d'avance,
Sylvain

**Comment by laurentabbal** [comment]
Bonjour,
Vous pouvez m'envoyer par email (à contact@codepuzzle.io) le code du devoir?

**Comment by Sylvain1978** [comment]
Bonjour, ce n'est pas un devoir mais une classe. Voci le lien de l'élève en question: https://www.codepuzzle.io/@/5YWSQALX

**Comment by Sylvain1978** [comment]
Bonjour, l'élève a bien utilisé le lien d'un autre élève...
