### ISSUE TITLE
Mode devoirs

### ISSUE THREAD

**Issue by Sylvain1978** [codepuzzle-io/www.codepuzzle.io#32]
Bonjour,
Je suis un fan de Code Puzzle que j'utilise beaucoup (puzzle, défi, devoirs, classe).
Ce serait top si on pouvait avoir plusieurs cellules dans les devoirs pour séparer les exercices.
merci d'avance,
Sylvain

**Comment by laurentabbal** [comment]
Bonjour,
C'est en cours de développement. Ca ressemblera à ça: https://www.codepuzzle.io/S2YTR4VL/copie

**Comment by Sylvain1978** [comment]
Impressionnant, j'ai hâte.

**Comment by laurentabbal** [comment]
C'est publié!
