### ISSUE TITLE
Onglet "defis" en vrac

### ISSUE THREAD

**Issue by jmzogit** [codepuzzle-io/www.codepuzzle.io#36]
hello,

Pouvez-vous réinitialiser et supprimer tous les "defis" sur mon profil, svp :  depuis mai 24, apres une fausse manip sur des caracteres speciaux, mon onglet "defis" m'affiche la tete de mort  ... 

merci par avance de votre réponse.

Jean-Marc Orione - Johannesburg

**Comment by laurentabbal** [comment]
Cela devrait être corrigé avec la nouvelle version.
