### ISSUE TITLE
Impossible de supprimer un devoir

### ISSUE THREAD

**Issue by tfontanet** [codepuzzle-io/www.codepuzzle.io#37]
Bonjour,
Quand je veux supprimer un devoir : 
- je clique sur la petite poubelle
- ça affiche deux boutons : "Confirmer" et "Annuler"
- je confirme

et ça ne supprime pas le devoir.
J'ai loupé quelque chose ?

Bien cordialement
Thibaud Fontanet

**Comment by tfontanet** [comment]
J'ajoute que quand je fais un clic droit - inspecter sur la poubelle pour afficher les outils de développement de mon navigateur (chromium sous linux) et que je copie colle dans la barre d'adresse le lien qui est sensé s'exécuter, ça supprime bien le devoir ;-)

**Comment by laurentabbal** [comment]
La nouvelle version corrige ce bug.
