### ISSUE TITLE
Accès aux défis

### ISSUE THREAD

**Issue by ebarbaud** [codepuzzle-io/www.codepuzzle.io#38]
Je ne peux plus accéder à ma page "DÉFIS"

J'ai tenté de mettre le caractère \ dans la description de la consigne de mon défi. Depuis, impossible d'accéder à ma page "DÉFIS".
https://www.codepuzzle.io/console/defis

![image](https://github.com/user-attachments/assets/a724d7d9-dc58-476a-8b2f-282eb3df6d16)

**Comment by ebarbaud** [comment]
En accédant spécifiquement à la page de modification via l'URL retrouvée dans mon historique, j'ai réussi à modifier mon "DÉFI" et à sauvegarder les modification : j'ai retrouvé l'accès à la page.

Cependant, le bug ne reste pas résolu : le caractère `\` semble faire planter les défis.

**Comment by laurentabbal** [comment]
La nouvelle version corrige ce bug.
