### ISSUE TITLE
Possibilité d'avoir deux zones pour un puzzle sans fausse ligne

### ISSUE THREAD

**Issue by swirly** [codepuzzle-io/www.codepuzzle.io#4]
Merci beaucoup pour l'outil

Au niveau cognitif, le fait d’avoir deux zones est intéressant, même s’il n’y a pas de lignes inutiles. Ça permet de choisir et de visualiser clairement la partie « rangée ». Serait il possible que la double zone puisse être une option

  -  choisie par le concepteur ?
   - choisie par l’élève ?
   -  et/ou utilisée si l a taille de l’écran le permet ?

D’un point de vue personnel, j’ai beaucoup plus de mal à ranger le puzzle avec une seule zone.

**Comment by laurentabbal** [comment]
Bonjour,

Je vais ajouter une option pour que le concepteur du puzzle puisse définir le mode d'affichage (simple ou double zone). Zou, sur la todo list. Sur un petit écran les deux zones se rangent automatiquement l'une en dessous de l'autre.

**Comment by swirly** [comment]
Merci !

**Comment by swirly** [comment]
Peut on espérer que cette amélioration soit faite pour le début de l'année ? Je voudrais concevoir des puzzles de révisions pour mes classes mais j'attends cette modification. Je vois qu'elle est dans la "in progress" depuis le 6 novembre.

Merci encore pour le travail et l'attention portée aux demandes

**Comment by laurentabbal** [comment]
Voila, c'est fait :-)
En cas de bug : https://github.com/codepuzzle-io/www.codepuzzle.io/issues

**Comment by swirly** [comment]
MERCI !
