### ISSUE TITLE
Problème d'affichage des "ACTIVITÉS DE LA CLASSE" sur la console élève

### ISSUE THREAD

**Issue by tfontanet** [codepuzzle-io/www.codepuzzle.io#41]
Bonjour,
Quand on crée une classe et qu'on y ajoute une seule activité, elle n'est pas visible dans la console des élèves. En revanche, dès que l'on ajoute une deuxième activité, les deux sont visibles sur la console élève ;-)

Merci pour ce superbe outil !
Thibaud Fontanet

**Comment by laurentabbal** [comment]
Merci. C'est corrigé!
